spring:
  web:
    whitelabel:
      enabled: true  # Set to false to disable the Whitel

output:
  ansi.enabled: always
jackson:
  default-property-inclusion: non_null

server:
  port: 1865
  error:
    include-message: ALWAYS